sudo: false
dist: bionic

services:
  - docker

addons:
    apt:
        packages:
            - freeglut3-dev
            - libgpiod-dev
            - libsdl2-dev
            - protobuf-compiler
            - python
            - python-pip
            - python-virtualenv
            - python3-dev
            - protobuf-compiler
            - libprotobuf-dev
            - libopencv-dev

language: cpp

matrix:
    include:
        - compiler: gcc
          env: BUILD_TYPE="tests" # compiles everything on linux, including master-firmware
        - compiler: gcc
          env: BUILD_TYPE="raspberry" # compiles master-firmware using the raspberry pi cross compiler
# Disabled until we figure out what to do with the cmake cross compile story
#        - compiler: gcc
#          env: BUILD_TYPE="build-cmake" PLATFORM="uwb-beacon"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="actuator"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="can-io"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="motor-control"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="proximity-beacon"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="sensor"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="uwb-beacon"
        - compiler: gcc
          env: BUILD_TYPE="computer-vision"

before_install:
    - git submodule update --init --recursive

install:
    - ci/install.sh

script:
    - ci/build.sh
